environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - node --version
  - npm --version
  - cmd: SET PATH=C:\MinGW\bin;%PATH%
  - npm run coverage
after_test:
  - node .\bin\codecov
build: off
